export const transactionsData = [
  {
    title: "Coffee Shop Purchase",
    cost: 4.75,
    date: "3 Jan 2025",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "Starbucks Coffee",
    summary: "Morning coffee at Starbucks.",
  },
  {
    title: "Grocery Store",
    cost: 67.32,
    date: "17 Feb 2025",
    category: "Groceries",
    isACH: false,
    appearsAs: "Whole Foods Market",
    summary: "Weekly grocery shopping at Whole Foods.",
  },
  {
    title: "Gas Station",
    cost: 45.89,
    date: "5 Dec 2024",
    category: "Transportation",
    isACH: false,
    appearsAs: "Shell Oil",
    summary: "Filled up gas tank at Shell.",
  },
  {
    title: "Online Subscription",
    cost: 9.99,
    date: "22 Mar 2025",
    category: "Entertainment",
    isACH: true,
    appearsAs: "Netflix",
    summary: "Monthly Netflix streaming subscription.",
  },
  {
    title: "Restaurant Dinner",
    cost: 34.56,
    date: "14 Nov 2024",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "Olive Garden",
    summary: "Dinner at Olive Garden restaurant.",
  },
  {
    title: "Pharmacy",
    cost: 12.43,
    date: "8 Apr 2025",
    category: "Health",
    isACH: false,
    appearsAs: "CVS Pharmacy",
    summary: "Prescription medication at CVS.",
  },
  {
    title: "Movie Tickets",
    cost: 24.5,
    date: "29 Jan 2025",
    category: "Entertainment",
    isACH: false,
    appearsAs: "AMC Theaters",
    summary: "Evening movie at AMC Theaters.",
  },
  {
    title: "Clothing Store",
    cost: 78.25,
    date: "11 May 2025",
    category: "Shopping",
    isACH: false,
    appearsAs: "H&M",
    summary: "New clothes from H&M.",
  },
  {
    title: "Fast Food",
    cost: 8.75,
    date: "2 Oct 2024",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "McDonald's",
    summary: "Quick lunch at McDonald's.",
  },
  {
    title: "Hardware Store",
    cost: 56.78,
    date: "19 Jun 2025",
    category: "Home",
    isACH: false,
    appearsAs: "Home Depot",
    summary: "Home repair supplies from Home Depot.",
  },
  {
    title: "Book Store",
    cost: 19.99,
    date: "7 Sep 2024",
    category: "Shopping",
    isACH: false,
    appearsAs: "Barnes & Noble",
    summary: "New books from Barnes & Noble.",
  },
  {
    title: "Uber Ride",
    cost: 15.67,
    date: "25 Feb 2025",
    category: "Transportation",
    isACH: true,
    appearsAs: "Uber",
    summary: "Uber ride across town.",
  },
  {
    title: "Parking Fee",
    cost: 5.0,
    date: "13 Jul 2025",
    category: "Transportation",
    isACH: false,
    appearsAs: "City Parking",
    summary: "Downtown parking fee.",
  },
  {
    title: "Electronics Store",
    cost: 89.99,
    date: "30 Dec 2024",
    category: "Shopping",
    isACH: false,
    appearsAs: "Best Buy",
    summary: "New headphones from Best Buy.",
  },
  {
    title: "Hair Salon",
    cost: 45.0,
    date: "16 Mar 2025",
    category: "Personal Care",
    isACH: false,
    appearsAs: "Supercuts",
    summary: "Haircut at Supercuts.",
  },
  {
    title: "Pet Store",
    cost: 32.45,
    date: "1 Aug 2024",
    category: "Pets",
    isACH: false,
    appearsAs: "PetSmart",
    summary: "Pet food and supplies at PetSmart.",
  },
  {
    title: "Office Supplies",
    cost: 23.56,
    date: "24 Apr 2025",
    category: "Shopping",
    isACH: false,
    appearsAs: "Staples",
    summary: "Office supplies for home workspace.",
  },
  {
    title: "Gym Membership",
    cost: 29.99,
    date: "9 Jan 2025",
    category: "Health & Fitness",
    isACH: true,
    appearsAs: "Planet Fitness",
    summary: "Monthly gym membership fee.",
  },
  {
    title: "Convenience Store",
    cost: 7.85,
    date: "28 Nov 2024",
    category: "Groceries",
    isACH: false,
    appearsAs: "7-Eleven",
    summary: "Late night snacks at 7-Eleven.",
  },
  {
    title: "Car Wash",
    cost: 12.0,
    date: "15 May 2025",
    category: "Auto",
    isACH: false,
    appearsAs: "Splash Car Wash",
    summary: "Deluxe car wash service.",
  },
  {
    title: "Bakery",
    cost: 8.5,
    date: "3 Oct 2024",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "Panera Bread",
    summary: "Breakfast at Panera Bread.",
  },
  {
    title: "Dentist Copay",
    cost: 25.0,
    date: "21 Jun 2025",
    category: "Health",
    isACH: true,
    appearsAs: "Bright Smile Dental",
    summary: "Regular dental checkup copay.",
  },
  {
    title: "Streaming Service",
    cost: 14.99,
    date: "6 Feb 2025",
    category: "Entertainment",
    isACH: true,
    appearsAs: "Hulu",
    summary: "Monthly Hulu subscription.",
  },
  {
    title: "Home Goods",
    cost: 67.89,
    date: "27 Jul 2024",
    category: "Home",
    isACH: false,
    appearsAs: "Bed Bath & Beyond",
    summary: "Kitchen supplies from Bed Bath & Beyond.",
  },
  {
    title: "Mobile Phone Bill",
    cost: 85.34,
    date: "12 Mar 2025",
    category: "Utilities",
    isACH: true,
    appearsAs: "Verizon Wireless",
    summary: "Monthly mobile phone service.",
  },
  {
    title: "Ice Cream Shop",
    cost: 6.75,
    date: "31 Aug 2024",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "Baskin-Robbins",
    summary: "Ice cream treats at Baskin-Robbins.",
  },
  {
    title: "Dry Cleaning",
    cost: 22.5,
    date: "18 Apr 2025",
    category: "Services",
    isACH: false,
    appearsAs: "Quick Clean",
    summary: "Dry cleaning for work clothes.",
  },
  {
    title: "Concert Tickets",
    cost: 75.0,
    date: "4 Jan 2025",
    category: "Entertainment",
    isACH: true,
    appearsAs: "Ticketmaster",
    summary: "Tickets for upcoming concert.",
  },
  {
    title: "Sporting Goods",
    cost: 49.99,
    date: "23 Sep 2024",
    category: "Shopping",
    isACH: false,
    appearsAs: "Dick's Sporting Goods",
    summary: "New running shoes from Dick's.",
  },
  {
    title: "Florist",
    cost: 35.0,
    date: "10 May 2025",
    category: "Gifts",
    isACH: false,
    appearsAs: "Blooms & Blossoms",
    summary: "Flower arrangement for Mother's Day.",
  },
  {
    title: "Shoe Store",
    cost: 64.5,
    date: "26 Dec 2024",
    category: "Shopping",
    isACH: false,
    appearsAs: "DSW",
    summary: "New dress shoes from DSW.",
  },
  {
    title: "Taxi Fare",
    cost: 18.75,
    date: "14 Jun 2025",
    category: "Transportation",
    isACH: false,
    appearsAs: "Yellow Cab",
    summary: "Taxi ride from airport.",
  },
  {
    title: "Charity Donation",
    cost: 10.0,
    date: "2 Feb 2025",
    category: "Charity",
    isACH: true,
    appearsAs: "Red Cross",
    summary: "Monthly donation to Red Cross.",
  },
  {
    title: "Veterinary Clinic",
    cost: 95.0,
    date: "20 Jul 2024",
    category: "Pets",
    isACH: false,
    appearsAs: "Healthy Pets Vet",
    summary: "Annual pet checkup and vaccines.",
  },
  {
    title: "Music Download",
    cost: 1.29,
    date: "7 Mar 2025",
    category: "Entertainment",
    isACH: true,
    appearsAs: "Apple iTunes",
    summary: "Single song purchase on iTunes.",
  },
  {
    title: "Pizza Delivery",
    cost: 22.95,
    date: "25 Aug 2024",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "Domino's Pizza",
    summary: "Pizza delivery for dinner.",
  },
  {
    title: "Tool Rental",
    cost: 38.5,
    date: "12 Apr 2025",
    category: "Home",
    isACH: false,
    appearsAs: "Ace Hardware",
    summary: "Weekend tool rental for home project.",
  },
  {
    title: "Bike Shop",
    cost: 52.75,
    date: "28 Nov 2024",
    category: "Shopping",
    isACH: false,
    appearsAs: "Trek Bicycle",
    summary: "Bike maintenance and new parts.",
  },
  {
    title: "Laundromat",
    cost: 4.5,
    date: "15 Jan 2025",
    category: "Services",
    isACH: false,
    appearsAs: "Wash & Fold",
    summary: "Laundry service while traveling.",
  },
  {
    title: "Toy Store",
    cost: 27.99,
    date: "3 Jun 2025",
    category: "Shopping",
    isACH: false,
    appearsAs: "Toys R Us",
    summary: "Birthday gift for nephew.",
  },
  {
    title: "ATM Withdrawal",
    cost: 40.0,
    date: "19 Oct 2024",
    category: "Cash",
    isACH: false,
    appearsAs: "Chase ATM",
    summary: "Cash withdrawal for weekend expenses.",
  },
  {
    title: "Eyeglasses",
    cost: 95.99,
    date: "8 Feb 2025",
    category: "Health",
    isACH: false,
    appearsAs: "LensCrafters",
    summary: "New prescription glasses.",
  },
  {
    title: "Jewelry Store",
    cost: 78.5,
    date: "24 Jul 2025",
    category: "Shopping",
    isACH: false,
    appearsAs: "Kay Jewelers",
    summary: "Anniversary gift purchase.",
  },
  {
    title: "Food Truck",
    cost: 11.25,
    date: "11 Mar 2025",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "Street Eats",
    summary: "Lunch from downtown food truck.",
  },
  {
    title: "Magazine Subscription",
    cost: 19.95,
    date: "29 Aug 2024",
    category: "Entertainment",
    isACH: true,
    appearsAs: "Conde Nast",
    summary: "Annual magazine subscription renewal.",
  },
  {
    title: "Craft Store",
    cost: 43.27,
    date: "16 Apr 2025",
    category: "Hobbies",
    isACH: false,
    appearsAs: "Michaels",
    summary: "Supplies for DIY home project.",
  },
  {
    title: "Bowling Alley",
    cost: 32.0,
    date: "5 Dec 2024",
    category: "Entertainment",
    isACH: false,
    appearsAs: "Strike Lanes",
    summary: "Bowling night with friends.",
  },
  {
    title: "Art Supplies",
    cost: 28.75,
    date: "22 May 2025",
    category: "Hobbies",
    isACH: false,
    appearsAs: "Blick Art Materials",
    summary: "Painting supplies for new hobby.",
  },
  {
    title: "Fitness Class",
    cost: 15.0,
    date: "9 Jan 2025",
    category: "Health & Fitness",
    isACH: false,
    appearsAs: "Orange Theory",
    summary: "Drop-in fitness class fee.",
  },
  {
    title: "Bagel Shop",
    cost: 5.49,
    date: "27 Jun 2024",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "Einstein Bros",
    summary: "Breakfast bagel and coffee.",
  },
  {
    title: "Garden Center",
    cost: 47.85,
    date: "13 Feb 2025",
    category: "Home",
    isACH: false,
    appearsAs: "Lowe's",
    summary: "Plants and gardening supplies.",
  },
  {
    title: "Parking Ticket",
    cost: 35.0,
    date: "30 Sep 2024",
    category: "Fees & Charges",
    isACH: true,
    appearsAs: "City Parking Authority",
    summary: "Parking violation fine payment.",
  },
  {
    title: "Furniture Store",
    cost: 99.99,
    date: "18 Apr 2025",
    category: "Home",
    isACH: false,
    appearsAs: "IKEA",
    summary: "New bookshelf for home office.",
  },
  {
    title: "Thrift Shop",
    cost: 12.75,
    date: "6 Nov 2024",
    category: "Shopping",
    isACH: false,
    appearsAs: "Goodwill",
    summary: "Vintage clothing finds at Goodwill.",
  },
  {
    title: "Smoothie Bar",
    cost: 7.25,
    date: "23 Mar 2025",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "Jamba Juice",
    summary: "Post-workout smoothie.",
  },
  {
    title: "Hotel Booking",
    cost: 89.0,
    date: "10 Aug 2024",
    category: "Travel",
    isACH: true,
    appearsAs: "Marriott Hotels",
    summary: "One-night hotel stay for business trip.",
  },
  {
    title: "Tire Shop",
    cost: 76.5,
    date: "28 Jan 2025",
    category: "Auto",
    isACH: false,
    appearsAs: "Discount Tire",
    summary: "New tire and rotation service.",
  },
  {
    title: "Museum Admission",
    cost: 18.0,
    date: "15 Jun 2025",
    category: "Entertainment",
    isACH: false,
    appearsAs: "Natural History Museum",
    summary: "Weekend visit to natural history museum.",
  },
  {
    title: "Bookstore Cafe",
    cost: 9.5,
    date: "1 Dec 2024",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "Books-A-Million",
    summary: "Coffee and pastry while book browsing.",
  },
  {
    title: "Fishing Supplies",
    cost: 42.35,
    date: "19 Apr 2025",
    category: "Hobbies",
    isACH: false,
    appearsAs: "Bass Pro Shops",
    summary: "New fishing gear for weekend trip.",
  },
  {
    title: "Phone Accessories",
    cost: 24.99,
    date: "7 Sep 2024",
    category: "Electronics",
    isACH: false,
    appearsAs: "T-Mobile",
    summary: "New phone case and screen protector.",
  },
  {
    title: "Yoga Studio",
    cost: 22.0,
    date: "24 Feb 2025",
    category: "Health & Fitness",
    isACH: true,
    appearsAs: "Yoga Works",
    summary: "Monthly unlimited yoga membership.",
  },
  {
    title: "Cooking Class",
    cost: 65.0,
    date: "11 Jul 2025",
    category: "Education",
    isACH: true,
    appearsAs: "Sur La Table",
    summary: "Italian cooking class registration.",
  },
  {
    title: "Vitamin Shop",
    cost: 33.45,
    date: "29 Dec 2024",
    category: "Health",
    isACH: false,
    appearsAs: "GNC",
    summary: "Vitamins and supplements purchase.",
  },
  {
    title: "Sports Event",
    cost: 55.0,
    date: "17 Mar 2025",
    category: "Entertainment",
    isACH: true,
    appearsAs: "StubHub",
    summary: "Basketball game tickets.",
  },
  {
    title: "Donut Shop",
    cost: 6.99,
    date: "4 Aug 2024",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "Dunkin' Donuts",
    summary: "Donuts and coffee for office meeting.",
  },
  {
    title: "Camera Store",
    cost: 87.5,
    date: "22 Jan 2025",
    category: "Electronics",
    isACH: false,
    appearsAs: "B&H Photo",
    summary: "Camera lens accessory purchase.",
  },
  {
    title: "Luggage Shop",
    cost: 79.95,
    date: "9 Jun 2025",
    category: "Shopping",
    isACH: false,
    appearsAs: "Samsonite",
    summary: "New carry-on suitcase for travel.",
  },
  {
    title: "Cake Bakery",
    cost: 28.5,
    date: "26 Nov 2024",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "Nothing Bundt Cakes",
    summary: "Birthday cake for celebration.",
  },
  {
    title: "Spa Treatment",
    cost: 85.0,
    date: "14 Apr 2025",
    category: "Personal Care",
    isACH: false,
    appearsAs: "Massage Envy",
    summary: "One-hour massage therapy session.",
  },
  {
    title: "Wine Shop",
    cost: 23.99,
    date: "2 Sep 2024",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "Total Wine",
    summary: "Wine purchase for dinner party.",
  },
  {
    title: "Locksmith",
    cost: 45.0,
    date: "20 Feb 2025",
    category: "Services",
    isACH: false,
    appearsAs: "Pop-A-Lock",
    summary: "Emergency lockout service.",
  },
  {
    title: "Pottery Studio",
    cost: 39.5,
    date: "8 Jul 2025",
    category: "Hobbies",
    isACH: false,
    appearsAs: "Clay Works",
    summary: "Pottery class session fee.",
  },
  {
    title: "Arcade",
    cost: 15.75,
    date: "25 Dec 2024",
    category: "Entertainment",
    isACH: false,
    appearsAs: "Dave & Buster's",
    summary: "Family fun at arcade and games.",
  },
  {
    title: "Aquarium Visit",
    cost: 29.5,
    date: "13 Mar 2025",
    category: "Entertainment",
    isACH: false,
    appearsAs: "National Aquarium",
    summary: "Tickets to aquarium exhibit.",
  },
  {
    title: "Watch Repair",
    cost: 55.0,
    date: "30 Aug 2024",
    category: "Services",
    isACH: false,
    appearsAs: "Time Fix",
    summary: "Battery replacement and watch cleaning.",
  },
  {
    title: "Camping Gear",
    cost: 67.25,
    date: "18 Jan 2025",
    category: "Outdoor",
    isACH: false,
    appearsAs: "REI",
    summary: "New tent and camping supplies.",
  },
  {
    title: "Cosmetics Store",
    cost: 32.99,
    date: "5 Jun 2025",
    category: "Personal Care",
    isACH: false,
    appearsAs: "Sephora",
    summary: "Makeup and skincare products.",
  },
  {
    title: "Cheese Shop",
    cost: 18.45,
    date: "23 Oct 2024",
    category: "Groceries",
    isACH: false,
    appearsAs: "Murray's Cheese",
    summary: "Specialty cheeses for wine tasting.",
  },
  {
    title: "Photo Printing",
    cost: 12.99,
    date: "10 Apr 2025",
    category: "Services",
    isACH: false,
    appearsAs: "Walgreens Photo",
    summary: "Vacation photo prints.",
  },
  {
    title: "Hiking Tour",
    cost: 45.0,
    date: "27 Sep 2024",
    category: "Outdoor",
    isACH: true,
    appearsAs: "Trail Adventures",
    summary: "Guided hiking tour in national park.",
  },
  {
    title: "Vinyl Records",
    cost: 27.5,
    date: "15 Feb 2025",
    category: "Entertainment",
    isACH: false,
    appearsAs: "Vinyl Revival",
    summary: "Classic rock album on vinyl.",
  },
  {
    title: "Candy Store",
    cost: 8.75,
    date: "3 Jul 2025",
    category: "Food & Drink",
    isACH: false,
    appearsAs: "See's Candies",
    summary: "Assorted chocolates gift box.",
  },
  {
    title: "Boat Rental",
    cost: 75.0,
    date: "21 Nov 2024",
    category: "Entertainment",
    isACH: true,
    appearsAs: "Lake Marina",
    summary: "Half-day boat rental at the lake.",
  },
  {
    title: "Ski Lift Ticket",
    cost: 85.0,
    date: "8 Mar 2025",
    category: "Entertainment",
    isACH: true,
    appearsAs: "Vail Resorts",
    summary: "Full-day ski pass at mountain resort.",
  },
  {
    title: "Tailoring Service",
    cost: 22.5,
    date: "26 Aug 2024",
    category: "Services",
    isACH: false,
    appearsAs: "Perfect Fit",
    summary: "Suit alterations for job interview.",
  },
  {
    title: "Karaoke Bar",
    cost: 35.0,
    date: "13 Jan 2025",
    category: "Entertainment",
    isACH: false,
    appearsAs: "Sing Out Loud",
    summary: "Private karaoke room with friends.",
  },
  {
    title: "Plant Nursery",
    cost: 29.99,
    date: "2 May 2025",
    category: "Home",
    isACH: false,
    appearsAs: "Garden World",
    summary: "Indoor houseplants for apartment.",
  },
  {
    title: "Driving Range",
    cost: 18.5,
    date: "19 Oct 2024",
    category: "Entertainment",
    isACH: false,
    appearsAs: "Top Golf",
    summary: "Golf practice session with bucket of balls.",
  },
  {
    title: "Sunglasses Kiosk",
    cost: 24.95,
    date: "7 Apr 2025",
    category: "Shopping",
    isACH: false,
    appearsAs: "Sunglass Hut",
    summary: "New sunglasses for spring season.",
  },
  {
    title: "Escape Room",
    cost: 32.0,
    date: "24 Sep 2024",
    category: "Entertainment",
    isACH: true,
    appearsAs: "Breakout Games",
    summary: "Team building escape room challenge.",
  },
  {
    title: "Pottery Barn",
    cost: 59.5,
    date: "12 Feb 2025",
    category: "Home",
    isACH: false,
    appearsAs: "Pottery Barn",
    summary: "Decorative pillows for living room.",
  },
  {
    title: "Candle Shop",
    cost: 17.25,
    date: "31 Jul 2025",
    category: "Shopping",
    isACH: false,
    appearsAs: "Yankee Candle",
    summary: "Scented candles for home.",
  },
  {
    title: "Surf Shop",
    cost: 49.99,
    date: "17 Dec 2024",
    category: "Shopping",
    isACH: false,
    appearsAs: "Billabong",
    summary: "Beach gear for upcoming vacation.",
  },
  {
    title: "Gourmet Food Store",
    cost: 38.75,
    date: "5 May 2025",
    category: "Groceries",
    isACH: false,
    appearsAs: "Dean & DeLuca",
    summary: "Specialty ingredients for dinner recipe.",
  },
  {
    title: "Bike Rental",
    cost: 25.0,
    date: "22 Oct 2024",
    category: "Entertainment",
    isACH: true,
    appearsAs: "City Bikes",
    summary: "Day-long bike rental for city tour.",
  },
  {
    title: "Mini Golf",
    cost: 12.5,
    date: "9 Mar 2025",
    category: "Entertainment",
    isACH: false,
    appearsAs: "Putt-Putt Fun Center",
    summary: "Family mini golf outing.",
  },
  {
    title: "Antique Store",
    cost: 65.0,
    date: "27 Aug 2024",
    category: "Shopping",
    isACH: false,
    appearsAs: "Vintage Treasures",
    summary: "Vintage decor item for home office.",
  },
];
